site_name: 植物日記
theme:
    name: material
    palette:
        primary: teal
        accent: pink
    features:
        - navigation.tabs
copyright: >
  <a href="#__consent">Change cookie settings</a>
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences 
    - pymdownx.tasklist:
        custom_checkbox: true
extra_css:
    - stylesheets/extra.css
extra_javascript:
    - js/consent.js
plugins:
    - awesome-pages
    - search:
        lang: ja
    - tags:
        tags_file: tags.md
    - blog:
        post_date_format: medium
        blog_dir: .
        blog_title: "My Wow"
extra:
    consent:
        title: Consent to view externally hosted resources
        description:
            Images are hosted on imgur.com. By clicking accept, you agree to make requests to imgur.com to download these images. If you do not accept, then images on this site will not be visible.
        cookies:
            imgur: Imgur downloads
